services:
  data-preparation:
    image: data-preparation:latest
    build: .
    command: snakemake --cores 10 report.txt
    #command: snakemake -R city_logic --cores 10 cities/download_report.txt    ### force a re-run of ENA table download ###
    #command: ["tail", "-f", "/dev/null"]                             ### keep container alive, snakemake has to be run via terminal-input ###
    volumes:
      - type: bind
        read_only: true
        source: ./database
        target: /snakemake/database
      - type: bind
        source: ./cities
        target: /snakemake/cities

  init-db:
    image: init-db
    build:
      dockerfile: ./database/initdb.Dockerfile
    command: ["./init_and_fill_db.sh"]
    volumes:
      - db-data:/app/data/db
      - type: bind
        read_only: true
        source: ./cities
        target: /app/cities

  sqlite:
    image: sqlite
    build:
      dockerfile: ./database/sqlite.Dockerfile
    #command: ["tail", "-f", "/dev/null"]
    ports:
      - "5001:5000"
    volumes:
      - db-data:/db
    restart: unless-stopped

  webapp:
    image: python:3.12-alpine
    working_dir: /app
    command: ["python", "-m", "http.server", "8000", "--bind", "0.0.0.0"]
    ports:
      - "8081:8000"
    volumes:
      - type: bind
        read_only: true
        source: ./webapp
        target: /app
    depends_on:
      - sqlite
    restart: unless-stopped

#  data-analysis:
#    image: data-analysis
#    build:
#      dockerfile: analysis.Dockerfile
#    volumes:
#      - type: bind
#        read_only: true
#        source: ./cities
#        target: /snakemake/cities

volumes:
  db-data: